#!/usr/bin/env sh

mkdir -p build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../src/platform/sdl_legacy/DingooToolchain.txt -DCMAKE_BUILD_TYPE=Relase -DBUILD_QT=OFF -DBUILD_SDL=OFF -DBUILD_SDL_LEGACY=ON -DBUILD_GL=OFF -DBUILD_GLES2=OFF -DBUILD_SHARED=OFF -DBUILD_STATIC=ON -DENABLE_SCRIPTING=OFF -DUSE_DEBUGGERS=OFF -DUSE_DISCORD_RPC=OFF -DUSE_EDITLINE=OFF -DUSE_ELF=OFF -DUSE_EPOXY=OFF -DUSE_FFMPEG=OFF -DUSE_GDB_STUB=OFF -DUSE_LIBZIP=OFF -DUSE_LZMA=OFF -DUSE_MINIZIP=OFF -DUSE_PNG=OFF -DUSE_SQLITE3=OFF ..
